### PR TITLE
Dtspo 9934 tf

### PR DESCRIPTION
**Pull request by mokainos**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Review by reespozzi — CHANGES_REQUESTED** [review]
Just a thought, should we keep commented code here uncommented in another dev branch and just commit the code we want to have in main for now? @mokainos

**Comment by mokainos** [comment]
> Just a thought, should we keep commented code here uncommented in another dev branch and just commit the code we want to have in main for now? @mokainos

 interest of time let's continue.

**Comment by darren221980** [comment]
I'd say leave it all in for now, easier to just un comment later.

The bits to be commented out should have a # insteasd of two //'s though.

**Review by reespozzi — APPROVED** [review]
Leaving comments in

**Pull request merged**
